# default dots config settings (read-only)

# core
dotfiles_path: $HOME/dotfiles

# misc
verbose: false

# theme
box:
  size: 72
  padding: 1
  style:
    - bold
    - lblue
  title:
    - bold
    - lblue
  char:
    # top_left: ┌
    # top_right: ┐
    # bottom_left: └
    # bottom_right: ┘
    top_left: ╭
    top_right: ╮
    bottom_left: ╰
    bottom_right: ╯
    fill_x: ─
    fill_y: │

success:
  icon:
    char: 
    style:
      - green
      - bold

sync:
  topic:
    icon:
      char: 
      style: lcyan
    style:
      - bold
      - uline
      - cyan

## main
main:
  option:
    max_width: 24
    command:
      - uline
      - yellow
    description: lgray
  sub_option:
    padding: 4
    command: normal
    description: lgray

## version
version:
  word: lgray
  number: bold
